---
title: "Rural"
output: html_document
date: '2022-06-30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(tigris)
```

I will be making a recreation of a map based on a tutorial to develop my skills programming in R.

```{r}
rural<-get_decennial(geography="state",
              variables=c("P001001","P002005"),
              year=2010,
              output="wide",
              geometry=TRUE)

rural

rural |> 
  filter(!(NAME=="Alaska")) |> 
  filter(!(NAME=="Hawaii")) |> 
  filter(!(NAME=="Puerto Rico")) |>
  ggplot(aes(fill=P002005/P001001 * 100))+
  geom_sf()+
  scale_fill_viridis_c(option="plasma",direction=-1)+
  theme_void()+
  labs(title="Rural geography of the United States",
       caption="Source: Census 2010",
       fill="Percent Rural")
```

```{r}
rural_shifted<-get_decennial(geography="state",
              variables=c("P001001","P002005"),
              year=2010,
              output="wide",
              geometry=TRUE) |> 
  shift_geometry()

rural_shifted |> 
  ggplot(aes(fill=P002005/P001001 * 100))+
  geom_sf()+
  scale_fill_viridis_c(option="plasma",direction=-1)+
  theme_void()+
  labs(title="Rural geography of the United States",
       caption="Source: Census 2010",
       fill="Percent Rural")
```

